Fixed missing include in psyfork/memoryutils.cpp
Error:
MemoryUtils.cpp: In member function ‘void* MemoryUtils::ResolveSymbol(void*, const char*)’:
MemoryUtils.cpp:249:43: error: ‘fstat’ was not declared in this scope
  if (dlfile == -1 || fstat(dlfile, &dlstat) == -1)

Fixed by adding missing include: #include <sys/stat.h>